// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://youiuudawtacihypxmji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdWl1dWRhd3RhY2loeXB4bWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODQ3NDEsImV4cCI6MjA2NDA2MDc0MX0.w1UTYcrBS2EgX7IraOjZtzMgJ90R4RnCiOTP1etICZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);